
# used with jinja2 functions cdn_js and cdn_css
# e.g. {{cdn_js('jquery') }} will embed a script link to
# the values here. Bump versions in this file
[jquery.js]
src = "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
integrity = "sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="

[bootstrap.js]
src = "https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
integrity = "sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"

[bootstrap.css]
href = "https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
integrity = "sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"

[bootstrap-icons.css]
href = "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css"
integrity = "sha256-4RctOgogjPAdwGbwq+rxfwAmSpZhWaafcZR9btzUk18="

[fontawesome5.js]
src = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/js/all.min.js"
integrity = "sha512-YSdqvJoZr83hj76AIVdOcvLWYMWzy6sJyIMic2aQz5kh2bPTd9dzY3NtdeEAzPp/PhgZqr4aJObB3ym/vsItMg=="

[fontawesome5.css]
href = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
integrity = "sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="

[fontawesome6.css]
href = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
integrity = "sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="

[fontawesome6.js]
src = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/js/all.min.js"
integrity = "sha512-naukR7I+Nk6gp7p5TMA4ycgfxaZBJ7MO5iC3Fp6ySQyKFHOGfpkSZkYVWV5R7u7cfAicxanwYQ5D1e17EfJcMA=="


[toastr.js] # at 2.1.4
# toastr requires jquery
src = "https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"
integrity = "sha256-yNbKY1y6h2rbVcQtf0b8lq4a+xpktyFc3pSYoGAY1qQ="

[toastr.css]
href = "https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css"
integrity = "sha256-R91pD48xW+oHbpJYGn5xR0Q7tMhH4xOrWn1QqMRINtA="

[bootstrap-select.js]
# src = "https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.12/dist/js/bootstrap-select.min.js"
# integrity = "sha256-+o/X+QCcfTkES5MroTdNL5zrLNGb3i4dYdWPWuq6whY="
src = "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.18/js/bootstrap-select.min.js"
integrity = "sha512-yDlE7vpGDP7o2eftkCiPZ+yuUyEcaBwoJoIhdXv71KZWugFqEphIS3PU60lEkFaz8RxaVsMpSvQxMBaKVwA5xg=="


[bootstrap-select.css]
# href = "https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.12/dist/css/bootstrap-select.min.css"
# integrity = "sha256-l3FykDBm9+58ZcJJtzcFvWjBZNJO40HmvebhpHXEhC0="
href = "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.18/css/bootstrap-select.min.css"
integrity = "sha512-ARJR74swou2y0Q2V9k0GbzQ/5vJ2RBSoCWokg4zkfM29Fb3vZEQyv0iWBMW/yvKgyHSR/7D64pFMmU8nYmbRkg=="

[nunjucks.js] # at 3.0.1
src = "https://cdnjs.cloudflare.com/ajax/libs/nunjucks/3.0.1/nunjucks.min.js"
integrity = "sha256-sh9FYQZVVLprCQB3/IcNyCRrZwu9hZ+xLHhUszDfsK4="

[nunjucks-slim.js]
# src = "https://mozilla.github.io/nunjucks/files/nunjucks-slim.js"
src = "https://unpkg.com/nunjucks@3.2.3/browser/nunjucks-slim.min.js"

[select2.js]  # at 4.0.13
src = "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/js/select2.min.js"
integrity = "sha256-wfVTTtJ2oeqlexBsfa3MmUoB77wDNRPqT1Q1WA2MMn4="

[select2.css]
href = "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/css/select2.min.css"
integrity = "sha256-FdatTf20PQr/rWg+cAKfl6j4/IY3oohFAJ7gVC3M34E="

[select2-bootstrap.css]
href = "https://cdn.jsdelivr.net/npm/@ttskch/select2-bootstrap4-theme@1.4.0/dist/select2-bootstrap4.min.css"
integrity = "sha256-3UPl0A8ykc7qW77XmHP0HDb1Nvs/09AACcTrNpIbdJ4="

[mathjax.js]
src = "https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-chtml.js"
integrity = "sha256-Cm3tWrvOEzMWWN0jnzQ4Kr0GSSx0txth6MqoES7FX6U="
async = true

[requirejs.js]
src = "https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js"
integrity = "sha256-Ae2Vz/4ePdIu6ZyI/5ZGsYnb+m0JlOmKPjt6XZ9JJkA="

[datatables.js]
src = "https://cdn.datatables.net/v/bs5/dt-1.12.1/datatables.min.js"

[datatables.css]
href = "https://cdn.datatables.net/v/bs5/dt-1.12.1/datatables.min.css"

[datatables-select.css]
href = "https://cdn.datatables.net/select/1.4.0/css/select.dataTables.min.css"

[datatables-select.js]
src = "https://cdn.datatables.net/select/1.4.0/js/dataTables.select.min.js"

[notyf.js]
# toast without jquery
src = "https://cdn.jsdelivr.net/npm/notyf@3.10.0/notyf.min.js"
integrity = "sha256-UnlpkMLasaTx2ZqovxBXUcQ5jq3oKXaZZ1aWENNFETE="

[notyf.css]
href = "https://cdn.jsdelivr.net/npm/notyf@3.10.0/notyf.min.css"
integrity = "sha256-IwkvZNRC/3S26O1gWwjBINmrPZ4zYvPX4z/98OKWHkQ="
